"""time_update

Revision ID: ba9456c12bf5
Revises: f7c136425fe0
Create Date: 2023-10-06 20:06:33.834394

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba9456c12bf5"
down_revision: Union[str, None] = "f7c136425fe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("tmp", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tmp")
    # ### end Alembic commands ###
