# Generated by Django 4.2.7 on 2023-11-11 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("innotter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="page_id",
            new_name="page",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="post_id",
            new_name="post",
        ),
    ]
