# Generated by Django 4.2.7 on 2024-12-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("innotter", "0002_rename_page_id_follower_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, default=None, null=True)),
                ("participants", models.PositiveIntegerField(default=0)),
                ("participants_limit", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("tags", models.ManyToManyField(to="innotter.tag")),
            ],
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="page",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="post",
            name="page",
        ),
        migrations.DeleteModel(
            name="Follower",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AddField(
            model_name="participant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="innotter.room"
            ),
        ),
    ]
