# Generated by Django 4.2.7 on 2024-12-14 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "innotter",
            "0003_participant_room_remove_like_post_remove_page_tags_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="datetime",
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
