# Generated by Django 4.2.7 on 2024-12-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innotter", "0005_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="category",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
