# Generated by Django 4.2.7 on 2024-12-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innotter", "0006_room_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="location",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
